### ISSUE TITLE
unknown oid 'vfs.zfs.min_auto_ashift'

### ISSUE THREAD

**Issue by xxdesmus** [fxlv/docs#1]
Running FreeBSD 10.2 on DO -- trying to follow this guide. Made the appropriate 10.1 -> 10.2 adjustments, when I go to begin the install I get the following:

`sysctl: unknown oid 'vfs.zfs.min_auto_ashift': No such file or directory`

I assumed it was related to the "Force 4K Sectors" option -- which defaults to YES ...so I toggled that off, but then instead I get:

`gpart: Permission denied`

any ideas?

**Comment by xxdesmus** [comment]
Stupid mistake. Don't mind me.

**Comment by fxlv** [comment]
So it all worked out in the end?
I haven't tried it with 10.2 myself, yet.

**Comment by fxlv** [comment]
Tried and updated the docs with FreeBSD 10.2.

**Comment by xxdesmus** [comment]
Working great now, thank you!

**Comment by githubDiversity** [comment]
I am running into the same issue while trying to install FreeBSD 12.1.release.
How did you solve it?

**Comment by BitingChaos** [comment]
> I am running into the same issue while trying to install FreeBSD 12.1.release.
> How did you solve it?

I just did a new FreeBSD 12.1 install and got the same error.
Why? **ZFS isn't loaded by default!** (The OID doesn't exist without the kernel module loaded.)

Before:
```
# sysctl vfs.zfs.min_auto_ashift
sysctl: unknown oid 'vfs.zfs.min_auto_ashift'
```
Enable ZFS and load module:
```
# sysrc zfs_enable=YES
# kldload zfs
```

Then check:

```
# sysctl vfs.zfs.min_auto_ashift
vfs.zfs.min_auto_ashift: 9
```
And set:
```
# sysctl vfs.zfs.min_auto_ashift=12
```
(don't forget to add that to /etc/sysctl.conf to make it persistent)

**Comment by githubDiversity** [comment]
@BitingChaos,

Thanks for the response, perhaps it will help someone in your scenario.

My scenario turned out to be that the disk I was trying to install on was in an unusable state (not sure which state, maybe locked or something)

I ended up booting ubuntu 19.10 from a bootable usb and used the gpartd GUI to wipe the disk. Then I went back and installed FreeBSD using the ZFS filesystem without issues.

I am not sure what's different in your scenario and mine (after having a good disk to install on) but I did not have to make any edits.
